version: '3.8'

services:
  app:
    image: yashs3324/portfolio:latest
    ports:
      - "4000:4000"
    environment:
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}

  # dev:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #   environment:
  #     - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
  #     - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
  #     - NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL}